version: '3.8'

services:
  db:
    image: postgres:14
    container_name: weather-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
